development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: koostoime_development
  pool: 5
  username: koostoime
  password: ohJummel
test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: koostoime_test
  pool: 5
  username: koostoime
  password: ohJummel
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: koostoime_production
  pool: 5
  username: koostoime
  password: ohJummel  
  
  
  username: mailis #koostoime
  password: maika #ohJummel 
